project:
  type: website
  output-dir: reports
  render:
    - README.md
    - notebooks/*.ipynb

format:
  html:
    theme: cosmo
    toc: true
    minimal: true
    code-copy: true
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px

number-sections: true

website:
  title: proks-salehin-et-al-2023
  sidebar:
    style: "docked"
    search: true
    contents: 
      - README.md
      - section: Reports
        contents: notebooks/*.ipynb
    tools:
      - icon: twitter
        href: https://twitter.com/LabBrickman
      - icon: github
        href: https://github.com/brickmanlab
